#!/usr/bin/env bash
source "$(dirname "$0")/setenv"
ulimit -s `ulimit -H -s`
if [ "$1" = "-kast" ]; then
  eval $JAVA org.kframework.main.Main '"$@"'
else
  # uncomment for Intellij remote debugger
  #eval $JAVA -agentlib:jdwp=transport=dt_socket,server=n,address=localhost:5005,suspend=y org.kframework.main.Main '"$@"'
  eval $JAVA org.kframework.main.Main '"$@"'
fi
